### ISSUE TITLE
[GitOps] CI/CD 방법론에 대한 고민 (ArgoCD VS FluxCD)

### ISSUE THREAD

**Issue by JunYupK** [JunYupK/CDC-PipeLine-With-Kafka#14]
# Push vs Pull 방식
CI/CD 구축하기 with K8S 강의를 들으면서 지금까지 모든 CI/CD 구축 방식을 Push 방식으로만 구현해왔다는 것을 알게되었습니다.
하지만 Gitops방법론에서는 Push 방식은 `추천하지 않는 방식이라고 합니다.` 그래서 이번 CI/CD는 Pull 방법으로도 배포를 진행해볼려고 합니다.

# CI/CD 파이프라인 현대화: Push에서 Pull 방식으로의 전환

## 1. 배경 및 문제 인식
현재 많은 조직에서 전통적인 Push 방식의 CI/CD 파이프라인을 사용하고 있습니다. 이 방식에서는 CI/CD 도구가 직접 Kubernetes 클러스터에 변경사항을 적용합니다. 하지만 이는 다음과 같은 잠재적인 문제를 가지고 있습니다:

- 보안 취약성: CI/CD 파이프라인이 프로덕션 클러스터에 직접 접근할 수 있는 권한을 가짐
- 상태 관리의 어려움: 실제 클러스터 상태와 원하는 상태의 차이를 추적하기 어려움
- 확장성 제한: 멀티 클러스터 환경에서 관리의 복잡성 증가

## 2. 제안하는 해결책
GitOps의 Pull 방식을 도입하여 이러한 문제들을 해결하고자 합니다. Pull 방식에서는:

1. GitHub Actions는 매니페스트 저장소만 업데이트
2. 클러스터 내부의 GitOps 오퍼레이터가 변경사항을 감지하고 적용
3. 자동 상태 조정 및 드리프트 감지 가능

### 3.1 현재 아키텍처 분석
```mermaid
graph LR
    A[GitHub] --> B[GitHub Actions]
    B -- kubectl apply --> C[K8s Cluster]
```

### 3.2 목표 아키텍처
```mermaid
graph LR
    A[GitHub] --> B[GitHub Actions]
    B --> D[Config Repo]
    E[GitOps Operator] --> D
    E --> C[K8s Cluster]
```

### 3.3 구현 단계
1. 설정 저장소 구조화
2. GitHub Actions 워크플로우 수정
3. GitOps 도구 선정 및 구축
4. 모니터링 및 알림 설정

## 4. GitOps 도구 선정

현재 고려중인 두 가지 주요 옵션:

### ArgoCD
- 강력한 UI/UX
- 풍부한 기능
- 상대적으로 높은 리소스 요구사항

### FluxCD
- 경량화된 구조
- 네이티브 Kubernetes 경험
- 모듈식 아키텍처

## 5. 기대효과
- 보안 강화: 클러스터 자격 증명 노출 최소화
- 안정성 향상: 자동화된 상태 조정
- 감사 용이성: Git 기반 변경 이력 관리
- 운영 효율성: 자동화된 배포 및 롤백

## 6. 향후 과제
- 팀 교육 및 적응 기간 필요
- 기존 파이프라인 마이그레이션 전략 수립
- 모니터링 및 알림 체계 구축

**Comment by JunYupK** [comment]
ArgoCD와 FluxCD에 대한 Claude의 답변입니다.

ArgoCD와 FluxCD를 자세히 비교해드리겠습니다. 두 도구 모두 Kubernetes를 위한 GitOps 도구이지만, 설계 철학과 구현 방식에서 중요한 차이가 있습니다.

## 아키텍처적 차이

ArgoCD는 단일 통합 애플리케이션으로 설계되었습니다. 핵심 서버, UI, 리포지토리 관리, 컨트롤러가 하나의 패키지로 제공됩니다. 이 통합된 접근 방식은 설치와 관리가 간단하지만, 유연성은 다소 제한될 수 있습니다.

반면 FluxCD는 마이크로서비스 아키텍처를 채택했습니다. 각 기능(소스 제어, 쿠버네티스 매니페스트 관리, Helm 관리, 알림 등)이 별도의 컨트롤러로 구현되어 있습니다. 이러한 모듈식 접근은 더 큰 유연성을 제공하지만, 초기 설정이 더 복잡할 수 있습니다.

## 사용자 인터페이스와 운영 경험

ArgoCD는 풍부한 웹 기반 UI를 제공합니다. 이 UI를 통해 배포 상태를 시각적으로 모니터링하고, 동기화 상태를 확인하며, 필요한 경우 수동 개입도 가능합니다. 예를 들어, 배포에 문제가 발생했을 때 UI에서 직접 롤백을 수행할 수 있습니다.

```yaml
# ArgoCD Application 예시
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/org/app.git
    targetRevision: HEAD
    path: k8s/production
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

FluxCD는 CLI 중심적인 접근을 택했습니다. 웹 UI는 기본적으로 제공되지 않으며, 모든 작업은 CLI나 Kubernetes 매니페스트를 통해 수행됩니다. 이는 자동화와 프로그래매틱한 제어에 더 적합할 수 있습니다.

```yaml
# FluxCD Configuration 예시
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: production-app
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/org/app
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: production-app
  namespace: flux-system
spec:
  interval: 5m
  path: ./k8s/production
  prune: true
  targetNamespace: production
  sourceRef:
    kind: GitRepository
    name: production-app
```

## 이미지 업데이트 자동화

ArgoCD의 이미지 업데이터는 별도의 컴포넌트로 제공되며, 주석 기반의 설정을 사용합니다. 이는 기존 Kubernetes 매니페스트를 크게 수정하지 않고도 이미지 자동화를 구현할 수 있게 해줍니다.

FluxCD는 이미지 자동화를 위한 전용 컨트롤러를 제공하며, 더 선언적인 접근 방식을 사용합니다. 이는 더 복잡한 정책과 규칙을 정의할 수 있게 해주지만, 추가적인 CRD들을 관리해야 합니다.

## 멀티클러스터 지원

ArgoCD는 멀티클러스터 관리를 위한 기능이 내장되어 있습니다. UI에서 여러 클러스터의 상태를 한눈에 확인하고 관리할 수 있습니다. 또한 클러스터 간 애플리케이션 복제나 마이그레이션도 상대적으로 쉽게 수행할 수 있습니다.

FluxCD는 멀티클러스터 시나리오를 위해 Flux Multi-tenancy를 제공하지만, 이를 구현하기 위해서는 더 많은 설정과 관리가 필요합니다. 각 클러스터는 독립적으로 관리되며, 중앙 집중식 관리를 위해서는 추가적인 도구나 사용자 정의 솔루션이 필요할 수 있습니다.

## 보안과 접근 제어

ArgoCD는 세밀한 RBAC(Role-Based Access Control)과 SSO 통합을 기본으로 제공합니다. 프로젝트 기반의 격리와 함께, 큰 조직에서 필요로 하는 대부분의 보안 기능을 즉시 사용할 수 있습니다.

FluxCD는 Kubernetes 네이티브 RBAC에 더 의존적입니다. 이는 더 단순하고 쿠버네티스와 일관된 보안 모델을 제공하지만, 엔터프라이즈 수준의 세밀한 접근 제어를 위해서는 추가적인 구성이 필요할 수 있습니다.

이러한 차이점들을 고려할 때, 어떤 도구를 선택할지는 조직의 구체적인 요구사항에 따라 달라질 수 있습니다. 시각적 관리와 즉시 사용 가능한 엔터프라이즈 기능이 중요하다면 ArgoCD가 좋은 선택일 것입니다. 반면, 더 프로그래매틱한 접근과 유연한 자동화가 중요하다면 FluxCD가 더 적합할 수 있습니다.
